config/routes.rb
Resta8::Application.routes.draw do
  resources :sales

  resources :products

  root :to => 'static_pages#home'
  
  resources :bookings
  resources :rooms
  resources :customers
  resources :hotels
  resources :orders
  resources :items

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :room
  belongs_to :customer
  belongs_to :hotel
  attr_accessible :booking_date, :booking_length, :hotel_id, :customer_id, :room_id
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :phone, :password, :secret_question, :secret_answer

  has_many :bookings, dependent: :destroy
  has_many :sales, dependent: :destroy
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  attr_accessible :address, :city, :email, :hotel_name, :phone, :website

  has_many :rooms, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name, :price

  has_many :orders, dependent: :destroy
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :item
  attr_accessible :quantity, :item_id



end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :brand, :category, :description, :model, :price, :subcategory

  has_many :sales, dependent: :destroy
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :hotel
  attr_accessible :room_name, :room_rate, :room_type, :hotel_id

  has_many :bookings, dependent: :destroy
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :product
  belongs_to :customer
  attr_accessible :credit_card_no, :discount, :quantity, :customer_id, :product_id
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController

  respond_to :html, :json, :xml

  def index
    @hotels = Hotel.paginate(page: params[:page])
    respond_with @hotels
  end

  def show
    @hotel = Hotel.find(params[:id])
    respond_with @hotel
  end

  def new
    @hotel = Hotel.new
  end


  def edit
    @hotel = Hotel.find(params[:id])
  end


  def create
    @hotel = Hotel.new(params[:hotel])
    @hotel.save
    respond_with @hotel
  end


  def update
    @hotel = Hotel.find(params[:id])
    @hotel.update_attributes(params[:hotel])
    respond_with @hotel
  end

  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy
    respond_with @hotel
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  respond_to :html, :json, :xml
  def index
    @items = Item.paginate(page: params[:page])
    respond_with @items
  end

  def show
    @item = Item.find(params[:id])
    respond_with @item
  end

  def new
    @item = Item.new
  end


  def edit
    @item = Item.find(params[:id])
  end


  def create
    @item = Item.new(params[:item])
    @item.save
    respond_with @item
  end

  def update
    @item = Item.find(params[:id])
    @item.update_attributes(params[:item])
    respond_with @item
  end


  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    respond_with @item
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  respond_to :html, :json, :xml

  def index
    @orders = Order.paginate(page: params[:page])
    #respond_with @orders
    respond_to do |format|
      format.html
      format.json do
        render :json => @orders.to_json(:include => { :item => { :only => :name}})
      end
    end
  end

  def show
    @order = Order.find(params[:id])
    # respond_with @order
    respond_to do |format|
      format.html
      format.json do
        render :json => @order.to_json(:include => { :item => { :only => :name}})
      end
    end
  end

  def new
    @order = Order.new
  end


  def edit
    @order = Order.find(params[:id])
  end


  def create
    @order = Order.new(params[:order])
    @order.save
    respond_with @order
  end


  def update
    @order = Order.find(params[:id])
    @order.update_attributes(params[:order])
    respond_with @order
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    respond_with @order
  end


end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  respond_to :html, :json, :xml

  def index
    @rooms = Room.paginate(page: params[:page])
    #respond_with @rooms
    respond_to do |format|
      format.html
      format.json do
        render :json => @rooms.to_json(:include => { :hotel => { :only => :hotel_name}})
        #render :json => @rooms.to_json(:include => { :hotel => { :only => [ :hotel_name, :city ]}})
        #render :json => @rooms.to_json(:include => [ :hotel])
      end
    end
  end

  def show
    @room = Room.find(params[:id])
    #respond_with @room
    respond_to do |format|
      format.html
      format.json do
        render :json => @room.to_json(:include => { :hotel => { :only => :hotel_name}})
      end
    end
  end

  def new
    @room = Room.new
  end


  def edit
    @room = Room.find(params[:id])
  end


  def create
    @room = Room.new(params[:room])
    @room.save
    respond_with @room
  end


  def update
    @room = Room.find(params[:id])
    @room.update_attributes(params[:room])
    respond_with @room
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    respond_with @room
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  respond_to :html, :json, :xml
  def index
    @sales = Sale.paginate(page: params[:page])
    #respond_with @sales
    respond_to do |format|
      format.html
      format.json do
        #render :json => @bookings.to_json(:include => [ :customer, :room])
        render :json => @sales.to_json(:include => [ :customer, {:product => { :only => :model}} ] )
      end
    end
  end

  def show
    @sale = Sale.find(params[:id])
    #respond_with @sale
    respond_to do |format|
      format.html
      format.json do
        #render :json => @bookings.to_json(:include => [ :customer, :room])
        render :json => @sale.to_json(:include => [ :customer, {:product => { :only => :model}} ] )
      end
    end
  end

  def new
    @sale = Sale.new
  end


  def edit
    @sale = Sale.find(params[:id])
  end


  def create
    @sale = Sale.new(params[:sale])
    @sale.save
    respond_with @sale
  end

  def update
    @sale = Sale.find(params[:id])
    @sale.update_attributes(params[:sale])
    respond_with @sale
  end


  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy
    respond_with @sale
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/hotels/_form.html.erb
<%= form_for(@hotel) do |f| %>
  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% @hotel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hotel_name %><br />
    <%= f.text_field :hotel_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>

<%= render 'form' %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<h1>Hotels</h1>
<%= link_to 'Add New Hotel', new_hotel_path %>
<br /><br />
<table class="table table-striped">
  <tr>
    <th>Hotel name</th>
    <th>Address</th>
    <th>City</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Website</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hotels.each do |hotel| %>
  <tr>
    <td><%= hotel.hotel_name %></td>
    <td><%= hotel.address %></td>
    <td><%= hotel.city %></td>
    <td><%= hotel.email %></td>
    <td><%= hotel.phone %></td>
    <td><%= hotel.website %></td>
    <td><%= link_to 'Show', hotel %></td>
    <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
    <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />


<%= will_paginate %>

app/views/hotels/new.html.erb
<h1>New hotel</h1>

<%= render 'form' %>

<%= link_to 'Back', hotels_path %>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Hotel name:</b>
  <%= @hotel.hotel_name %>
</p>

<p>
  <b>Address:</b>
  <%= @hotel.address %>
</p>

<p>
  <b>City:</b>
  <%= @hotel.city %>
</p>

<p>
  <b>Email:</b>
  <%= @hotel.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @hotel.phone %>
</p>

<p>
  <b>Website:</b>
  <%= @hotel.website %>
</p>


<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Menu Items</h1>
<%= link_to 'Add New Item', new_item_path %>
<br /><br />
<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.name %></td>
    <td><%= item.price %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= will_paginate %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Price:</b>
  <%= @item.price %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item %><br />
    <%= f.collection_select(:item_id, Item.all, :id, :name ) %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Restaurant Orders</h1>
<%= link_to 'Add New Order', new_order_path %>
<br /><br />
<table class="table table-striped">
  <tr>
    <th>Order_ID</th>
    <th>Item</th>
    <th>Quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.id %></td>
    <td><%= order.item.name %></td>
    <td><%= order.quantity %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />


<%= will_paginate %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Order_ID:</b>
  <%= @order.id %>
</p>

<p>
  <b>Item:</b>
  <%= @order.item.name %>
</p>

<p>
  <b>Quantity:</b>
  <%= @order.quantity %>
</p>




<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hotel %><br />
    <%= f.collection_select(:hotel_id, Hotel.all, :id, :hotel_name ) %>
  </div>
  <div class="field">
    <%= f.label :room_name %><br />
    <%= f.text_field :room_name %>
  </div>
  <div class="field">
    <%= f.label :room_type %><br />
    <%= f.text_field :room_type %>
  </div>
  <div class="field">
    <%= f.label :room_rate %><br />
    <%= f.text_field :room_rate %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h1>Hotel Rooms</h1>
<%= link_to 'Add New Room', new_room_path %>
<br /><br />
<table class="table table-striped">
  <tr>
    <th>Hotel</th>
    <th>Room name</th>
    <th>Room type</th>
    <th>Room rate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rooms.each do |room| %>
  <tr>
    <td><%= room.hotel.hotel_name %></td>
    <td><%= room.room_name %></td>
    <td><%= room.room_type %></td>
    <td><%= room.room_rate %></td>
    <td><%= link_to 'Show', room %></td>
    <td><%= link_to 'Edit', edit_room_path(room) %></td>
    <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />


<%= will_paginate %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Hotel:</b>
  <%= @room.hotel.hotel_name %>
</p>
<p>
  <b>Room name:</b>
  <%= @room.room_name %>
</p>
<p>
  <b>Room type:</b>
  <%= @room.room_type %>
</p>
<p>
  <b>Room rate:</b>
  <%= @room.room_rate %>
</p>






<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer %><br />
    <%= f.collection_select(:customer_id, Customer.all, :id, :first_name ) %>
  </div>
  <div class="field">
    <%= f.label :product %><br />
    <<%= f.collection_select(:product_id, Product.all, :id, :model ) %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :credit_card_no %><br />
    <%= f.text_field :credit_card_no %>
  </div>
  <div class="field">
    <%= f.label :discount %><br />
    <%= f.text_field :discount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<h1>Store Sales</h1>
<%= link_to 'Add New Sale', new_sale_path %>
<br /><br />
<table class="table table-striped">
  <tr>
    <th>Customer</th>
    <th>Product</th>
    <th>Quantity</th>
    <th>Credit card no</th>
    <th>Discount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sales.each do |sale| %>
  <tr>
    <td><%= sale.customer.first_name %></td>
    <td><%= sale.product.model %></td>
    <td><%= sale.quantity %></td>
    <td><%= sale.credit_card_no %></td>
    <td><%= sale.discount %></td>
    <td><%= link_to 'Show', sale %></td>
    <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
    <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>




<%= will_paginate %>

app/views/sales/new.html.erb
<h1>New sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Customer:</b>
  <%= @sale.customer.first_name %>
</p>

<p>
  <b>Product:</b>
  <%= @sale.product.model %>
</p>

<p>
  <b>Quantity:</b>
  <%= @sale.quantity %>
</p>

<p>
  <b>Credit card no:</b>
  <%= @sale.credit_card_no %>
</p>

<p>
  <b>Discount:</b>
  <%= @sale.discount %>
</p>

x


<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>