config/routes.rb
Resta8::Application.routes.draw do
  resources :sales

  resources :products

  root :to => 'static_pages#home'
  
  resources :bookings
  resources :rooms
  resources :customers
  resources :hotels
  resources :orders
  resources :items

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :room
  belongs_to :customer
  belongs_to :hotel
  attr_accessible :booking_date, :booking_length, :hotel_id, :customer_id, :room_id
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :phone, :password, :secret_question, :secret_answer

  has_many :bookings, dependent: :destroy
  has_many :sales, dependent: :destroy
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  attr_accessible :address, :city, :email, :hotel_name, :phone, :website

  has_many :rooms, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name, :price

  has_many :orders, dependent: :destroy
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :item
  attr_accessible :quantity, :item_id



end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :brand, :category, :description, :model, :price, :subcategory

  has_many :sales, dependent: :destroy
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :hotel
  attr_accessible :room_name, :room_rate, :room_type, :hotel_id

  has_many :bookings, dependent: :destroy
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :product
  belongs_to :customer
  attr_accessible :credit_card_no, :discount, :quantity, :customer_id, :product_id
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  respond_to :html, :json, :xml
  def index
    @items = Item.paginate(page: params[:page])
    respond_with @items
  end

  def show
    @item = Item.find(params[:id])
    respond_with @item
  end

  def new
    @item = Item.new
  end


  def edit
    @item = Item.find(params[:id])
  end


  def create
    @item = Item.new(params[:item])
    @item.save
    respond_with @item
  end

  def update
    @item = Item.find(params[:id])
    @item.update_attributes(params[:item])
    respond_with @item
  end


  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    respond_with @item
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  respond_to :html, :json, :xml

  def index
    @rooms = Room.paginate(page: params[:page])
    #respond_with @rooms
    respond_to do |format|
      format.html
      format.json do
        render :json => @rooms.to_json(:include => { :hotel => { :only => :hotel_name}})
        #render :json => @rooms.to_json(:include => { :hotel => { :only => [ :hotel_name, :city ]}})
        #render :json => @rooms.to_json(:include => [ :hotel])
      end
    end
  end

  def show
    @room = Room.find(params[:id])
    #respond_with @room
    respond_to do |format|
      format.html
      format.json do
        render :json => @room.to_json(:include => { :hotel => { :only => :hotel_name}})
      end
    end
  end

  def new
    @room = Room.new
  end


  def edit
    @room = Room.find(params[:id])
  end


  def create
    @room = Room.new(params[:room])
    @room.save
    respond_with @room
  end


  def update
    @room = Room.find(params[:id])
    @room.update_attributes(params[:room])
    respond_with @room
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    respond_with @room
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<br/><br/><br/>
<footer class="footer">
  <small>
    <a href="#">Apps</a>
    by Dust Rise Technologies
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Dust Rise", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>

            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Hotel App <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Customers", customers_path %></li>
                <li><%= link_to "Hotels", hotels_path %></li>
                <li><%= link_to "Rooms", rooms_path %></li>
                <li><%= link_to "Bookings", bookings_path %></li>
              </ul>
            </li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Restaurant App <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Items", items_path %></li>
                <li><%= link_to "Orders", orders_path %></li>
              </ul>
            </li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Store App <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Customers", customers_path %></li>
                <li><%= link_to "Products", products_path %></li>
                <li><%= link_to "Sales", sales_path %></li>
              </ul>
            </li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DR</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      
    </div>
  </body>
</html>